apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-rest-tasker
spec:
  selector:
    matchLabels:
      lbtype: external
  replicas: 1
  template:
    metadata:
      labels:
        lbtype: external
        app: api-rest-tasker
    spec:
      containers:
      - name: api-rest-tasker
        image: eu-marseille-1.ocir.io/axds7s98uqrj/simple-task/api-rest-tasker:1.0
        imagePullPolicy: Always
        command:
          - java
          - -jar
          - /opt/app/api-rest-tasker-1.0.jar
          - server
          - config.yml
        env:
          - name: DBHOST
            value: ddbb
        ports:
        - name: "api-rest-tasker"
          containerPort: 8080
      imagePullSecrets:
        - name: ocirsecret          
