apiVersion: v1
kind: Service
metadata:
  name: ui-tasker-lb
  labels:
    app: tasker
spec:
  type: LoadBalancer
  loadBalancerIP: 129.151.224.74
  ports:
    - name: "ui-tasker"
      port: 80
      targetPort: "ui-tasker"
    - name: "api-rest-tasker"
      port: 8080
      targetPort: "api-rest-tasker"      
  selector:
    lbtype: external
