apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-tasker
spec:
  selector:
    matchLabels:
      lbtype: external
  replicas: 1
  template:
    metadata:
      labels:
        lbtype: external
        app: ui-tasker
    spec:
      containers:
      - name: ui-tasker
        image: eu-marseille-1.ocir.io/axds7s98uqrj/simple-task/ui-tasker:1.0
        imagePullPolicy: Always
        # Take this Ip or domain from a configmap that gets the value from terraform or some automated script, never hardcoded
        env:
          - name: BASEPATH_BE
            value: http://129.151.224.74:8080
        ports:
        - name: "ui-tasker"
          containerPort: 80
      imagePullSecrets:
        - name: ocirsecret
