apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-tasker
spec:
  selector:
    matchLabels:
      app: ui-tasker
  replicas: 1
  template:
    metadata:
      labels:
        app: ui-tasker
    spec:
      containers:
      - name: ui-tasker
        image: eu-marseille-1.ocir.io/axds7s98uqrj/simple-task/ui-tasker:latest
        imagePullPolicy: Always
        env:
          - name: BASEPATH_BE
            value: http://api-rest-tasker:8080
        ports:
        - name: app
          containerPort: 80
      imagePullSecrets:
        - name: ocirsecret
